#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Nov 26 12:26:45 2023

@author: tfaraon

main script to use the Readers and plot some things
"""

### Load the modules 
import D3D_FLOW_reader as ft
import D3D_WAVE_reader as wt
import numpy as np


#Define paths to netcdf 
Wave_file = "/home/tfaraon/Documents/Cours/delft3D/V1/wavm-synthetic.nc"
Flow_file = '/home/tfaraon/Documents/Cours/delft3D/V1/trim-synthetic.nc'

#Create classes for each dataset
WAVE = wt.D3D_Wave_Loader(Wave_file)
FLOW = ft.D3D_Flow_Loader(Flow_file)

#Exemple of a way to access data 
for t in np.arange(len(FLOW.time.data )): 
    ft.map_data(FLOW, FLOW.TAUMAX, t)

#Exemple of a way to plot
wt.plot_sub(WAVE.wlength)
